apiVersion: batch/v1
kind: Job
metadata:
  name: htmlupdate
  namespace: simple-nginx
spec:
  # ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
      - name: git-clone
        image: nokkie/alpinegit:arm64
        args:
        - git 
        - clone
        - https://gitlab.digitalinfo.nl/generic/simple-html.git
        - /usr/share/nginx/html
        securityContext:
          runAsUser: 1 
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        emptyDir: {}
